VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SampleAnnotSheet"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit
'@IgnoreModule ProcedureNotUsed
'@Folder("Sheets")

'' Function: AutofillBySampleType_Click
'' --- Code
''  Private Sub AutofillBySampleType_Click()
'' ---
''
'' Description:
''
'' Function that controls what happens when the following button is
'' left clicked.
''
'' (see Sample_Annot_Autofill_By_Sample_Type_Button.png)
''
'' Currently, it calls the function Sample_Annot_Buttons.Autofill_By_Sample_Type_Click
''
'' See documentation of this function for more information.
''
Private Sub AutofillBySampleType_Click()
    Sample_Annot_Buttons.Autofill_By_Sample_Type_Click
End Sub

'' Function: LoadSampleAnnotationRaw_Click
'' --- Code
''  Private Sub LoadSampleAnnotationRaw_Click()
'' ---
''
'' Description:
''
'' Function that controls what happens when the following button is
'' left clicked.
''
'' (see Sample_Annot_Load_Sample_Annot_Raw_Column_Name_Button.png)
''
'' Currently, it calls the function Sample_Annot_Buttons.Load_Sample_Annot_Raw_Column_Name_Click
''
'' See documentation of this function for more information.
''
Private Sub LoadSampleAnnotationRaw_Click()
    Sample_Annot_Buttons.Load_Sample_Annot_Raw_Column_Name_Click
End Sub

'' Function: LoadSampleAnnotationTidy_Click
'' --- Code
''  Private Sub LoadSampleAnnotationTidy_Click()
'' ---
''
'' Description:
''
'' Function that controls what happens when the following button is
'' left clicked.
''
'' (see Sample_Annot_Load_Sample_Annot_Tidy_Column_Name_Button.png)
''
'' Currently, it calls the function Sample_Annot_Buttons.Load_Sample_Annot_Tidy_Column_Name_Click
''
'' See documentation of this function for more information.
''
Private Sub LoadSampleAnnotationTidy_Click()
    Sample_Annot_Buttons.Load_Sample_Annot_Tidy_Column_Name_Click
End Sub

'' Function: AutofillSampleType_Click
'' --- Code
''  Private Sub AutofillSampleType_Click()
'' ---
''
'' Description:
''
'' Function that controls what happens when the following button is
'' left clicked.
''
'' (see Sample_Annot_Autofill_Sample_Type_Button.png)
''
'' Currently, it calls the function Sample_Annot_Buttons.Autofill_Sample_Type_Click
''
'' See documentation of this function for more information.
''
Private Sub AutofillSampleType_Click()
    Sample_Annot_Buttons.Autofill_Sample_Type_Click
End Sub

'' Function: AutofillConcentrationUnit_Click
'' --- Code
''  Private Sub AutofillConcentrationUnit_Click()
'' ---
''
'' Description:
''
'' Function that controls what happens when the following button is
'' left clicked.
''
'' (see Sample_Annot_Autofill_Concentration_Unit_Button.png)
''
'' Currently, it calls the function Sample_Annot_Buttons.Autofill_Concentration_Unit_Click
''
'' See documentation of this function for more information.
''
Private Sub AutofillConcentrationUnit_Click()
    Sample_Annot_Buttons.Autofill_Concentration_Unit_Click
End Sub

'' Function: ClearSampleTable_Click
'' --- Code
''  Private Sub ClearSampleTable_Click()
'' ---
''
'' Description:
''
'' Function that controls what happens when the following button is
'' left clicked.
''
'' (see Sample_Annot_Clear_Columns_Button.png)
''
'' Currently, it calls the function Sample_Annot_Buttons.Clear_Sample_Table_Click
''
'' See documentation of this function for more information.
''
Private Sub ClearSampleTable_Click()
    Sample_Annot_Buttons.Clear_Sample_Table_Click
End Sub

'' Function: LoadSampleNameToDilution_Click
'' --- Code
''  Private Sub LoadSampleNameToDilution_Click()
'' ---
''
'' Description:
''
'' Function that controls what happens when the following button is
'' left clicked.
''
'' (see Sample_Annot_Load_Sample_Name_To_Dilution_Annot_Button.png)
''
'' Currently, it calls the function Sample_Annot_Buttons.Load_Sample_Name_To_Dilution_Annot_Click
''
'' See documentation of this function for more information.
''
Private Sub LoadSampleNameToDilution_Click()
    Sample_Annot_Buttons.Load_Sample_Name_To_Dilution_Annot_Click
End Sub

